image: vitalelement/avalonci:latest
before_script:
  
AvalonStudio:
  script:     
  # update all submodules.
  - git submodule update --init
  
  - cd AvalonStudio
  - ./dependencies.sh
  - ./buildmono.sh