sudo: required
os:
  - linux
dist: trusty

script:
  - wget https://dotnetcli.blob.core.windows.net/dotnet/master/Installers/Latest/dotnet-host-ubuntu-x64.latest.deb
  - wget https://dotnetcli.blob.core.windows.net/dotnet/master/Installers/Latest/dotnet-hostfxr-ubuntu-x64.latest.deb
  - wget https://dotnetcli.blob.core.windows.net/dotnet/master/Installers/Latest/dotnet-sharedframework-ubuntu-x64.latest.deb
  - wget https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-ubuntu-x64.latest.deb
  - sudo dpkg -i dotnet-host-ubuntu-x64.latest.deb
  - sudo dpkg -i dotnet-hostfxr-ubuntu-x64.latest.deb
  - sudo dpkg -i dotnet-sharedframework-ubuntu-x64.latest.deb
  - sudo dpkg -i dotnet-sdk-ubuntu-x64.latest.deb
  - dotnet --info
  - ./build.sh --configuration "Release"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/abf03510b7719b383e2b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: never
