sudo: required
os:
  - linux
dist: trusty

script:
  - mkdir dotnet
  - cd dotnet
  - wget https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-dev-ubuntu-x64.latest.tar.gz
  - tar -xvzf dotnet-dev-ubuntu-x64.latest.tar.gz
  - PATH="$PATH:$HOME/dotnet"
  - dotnet --info
  - ./build.sh --configuration "Release"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/abf03510b7719b383e2b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: never