sudo: required
os:
  - linux
dist: xenial

script:
  - sudo apt-get install -y libunwind8 libcurl3
  - wget http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu52_52.1-8ubuntu0.2_amd64.deb
  - sudo dpkg -i libicu52_52.1-8ubuntu0.2_amd64.deb
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list' 
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install dotnet-dev-2.0.0-preview1-005743
  - dotnet --info
  - ./build.sh --configuration "Release"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/abf03510b7719b383e2b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: never
