version: 0.4.0.{build}
os: Visual Studio 2017
install:  

clone_script:
- cmd: >-
    git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
    cd %APPVEYOR_BUILD_FOLDER%
    git checkout -qf %APPVEYOR_REPO_COMMIT%
    git submodule sync
    git submodule update --init --recursive

build_script:
- cmd: dotnet --info
- ps: $url1='https://img.shields.io/badge/version-v0.4.' + $env:APPVEYOR_BUILD_NUMBER  + '-blue.svg'
- ps: .\download.ps1 $url1 "latest-version-badge.svg"
- ps: .\build.ps1

test: off

artifacts:
- path: artifacts/zip/*.zip
- path: artifacts/nuget/*.nupkg
- path: latest-version-badge.svg

deploy:
- provider: Environment
  name: FastRing
  on:
    branch: master
    APPVEYOR_REPO_TAG: true

notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/e8ce2449e773a183903b
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true

cache:

