version: 0.2.0.{build}
os: Visual Studio 2015
install:
  - if not exist dotnet-dev-win-x64.latest.zip appveyor DownloadFile https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-dev-win-x64.latest.zip -FileName "dotnet-dev-win-x64.latest.zip"  
  - cmd: 7z x -o c:\dotnet

before_build:
- cmd: path c:\dotnet
- cmd: dotnet --info  
- cmd: >-
    git submodule update --init --recursive

build_script:
- cmd: dotnet --info
- ps: path c:\dotnet
- ps: $url1='https://img.shields.io/badge/version-v0.2.' + $env:APPVEYOR_BUILD_NUMBER  + '-blue.svg'
- ps: .\download.ps1 $url1 "latest-version-badge.svg"
- ps: .\build.ps1

test: off

artifacts:
- path: artifacts/zip/AvalonStudio-win7-x64.zip
- path: artifacts/zip/AvalonStudioBuild-win7-x64.zip
- path: artifacts/zip/AvalonStudio-ubuntu.14.04-x64.zip
- path: artifacts/zip/AvalonStudioBuild-ubuntu.14.04-x64.zip
- path: artifacts/zip/AvalonStudio-debian.8-x64.zip
- path: artifacts/zip/AvalonStudioBuild-debian.8-x64.zip
- path: artifacts/zip/AvalonStudio-osx.10.12-x64.zip
- path: artifacts/zip/AvalonStudioBuild-osx.10.12-x64.zip
- path: latest-version-badge.svg

deploy:
- provider: Environment
  name: FastRing
  on:
    branch: master
    APPVEYOR_REPO_TAG: true

notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/e8ce2449e773a183903b
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
